name: scores_2_go
description: "Open Source Medical Scoring App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  google_fonts: ^6.3.1
  package_info_plus: ^8.3.1
  supabase_flutter: ^2.10.2
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  stream_transform: ^2.1.1
  intl: any
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/bmc-button.svg
    - assets/bmc-logo.svg
    - assets/app_icon.svg
    - lib/data/scores/definitions/demo-score/
    - lib/data/scores/definitions/apache-ii/
    - lib/data/scores/definitions/saps-ii/
    - lib/data/scores/definitions/sofa/
    - lib/data/scores/definitions/rass/
    - lib/data/scores/definitions/ramsay/
    - lib/data/scores/definitions/saps-3/
    - lib/data/scores/definitions/euroscore/
    - lib/data/scores/definitions/gcs/
    - lib/data/scores/definitions/meld/
    - lib/data/scores/definitions/finnegan/
    - lib/data/scores/definitions/mods/
    - lib/data/scores/definitions/horovitz/